spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19960412Clh
    url: jdbc:mysql://127.0.0.1/sell?characterEncoding=utf-8&userSSL=false
  jpa:
    show-sql: true
server:
  port: 8080
  servlet:
    context-path: /sell
